/*
 * Second Mile ESE Compliance Visit — checklist rules database
 * Version-controlled. Every citation ships as "Pending Verification" until a
 * reviewer confirms it against the authoritative source (eCFR, Florida
 * Administrative Code, Florida Statutes, or the district's current form).
 * District-specific references are intentionally blank until verified.
 *
 * show: conditions for displaying an item on a student file
 *   events:    only these IEP event types
 *   notEvents: hide for these IEP event types
 *   flag:      only when this file flag is on
 *   minAge:    number, or "transition" (uses Settings > transition start age)
 * fix: suggested default for where a finding is corrected
 *   now | meeting | system | evidence
 */
window.SM_RULES = {
  version: '2026.10-draft1',
  updated: '2026-10-07',
  sections: [
    { id: 'A', title: 'IEP timelines and eligibility' },
    { id: 'B', title: 'Meeting documentation' },
    { id: 'C', title: 'IEP content' },
    { id: 'D', title: 'Transition' },
    { id: 'E', title: 'Service implementation' }
  ],
  items: [
    // A. Timelines and eligibility
    { id: 'A1', section: 'A', title: 'Annual IEP review', critical: true, fix: 'meeting',
      show: { notEvents: ['initial'] },
      verify: 'The IEP was reviewed within one year of the previous IEP meeting date.',
      where: 'IEP cover page and the IEP history in the district system.',
      evidence: ['Previous IEP meeting date located', 'Current IEP meeting date located', 'Interval checked against the one-year limit'],
      source: '34 CFR §300.324(b)(1)(i)', status: 'Pending Verification', district: '' },
    { id: 'A2', section: 'A', title: 'Current IEP documentation', critical: true, fix: 'now',
      verify: 'An IEP is in effect on the review date and a copy is available for the reviewer.',
      where: 'Student folder or district system.',
      evidence: ['IEP effective dates located', 'IEP is current on the review date', 'Copy available in folder or system'],
      source: '34 CFR §300.323(a)', status: 'Pending Verification', district: '' },
    { id: 'A3', section: 'A', title: 'Reevaluation timeline', critical: true, fix: 'meeting',
      show: { notEvents: ['initial'] },
      verify: 'A reevaluation or reevaluation determination happened within three years of the last evaluation.',
      where: 'Reevaluation plan or determination in the district system.',
      evidence: ['Last evaluation date located', 'Reevaluation due date checked', 'Reevaluation determination located if completed'],
      source: '34 CFR §300.303(b)(2)', status: 'Pending Verification', district: '' },
    { id: 'A4', section: 'A', title: 'Eligibility documentation', fix: 'evidence',
      show: { events: ['initial', 'reeval', 'transfer'] },
      verify: 'An eligibility determination exists and matches the exceptionality on the IEP.',
      where: 'Eligibility staffing or determination record.',
      evidence: ['Eligibility determination located', 'Determination date checked', 'Exceptionality matches the IEP'],
      source: '34 CFR §300.306; Fla. Admin. Code R. 6A-6.0331', status: 'Pending Verification', district: '' },
    { id: 'A5', section: 'A', title: 'Required consent', critical: true, fix: 'evidence',
      show: { events: ['initial', 'reeval'] },
      verify: 'Informed consent is on file for the evaluation, reevaluation, or initial provision of services, as applicable.',
      where: 'Consent forms in the folder or district system.',
      evidence: ['Consent form located', 'Consent type matches the event', 'Consent date precedes the activity'],
      source: '34 CFR §300.300', status: 'Pending Verification', district: '' },
    { id: 'A6', section: 'A', title: 'Transfer review', fix: 'meeting',
      show: { events: ['transfer'] },
      verify: 'Comparable services were provided and the prior IEP was adopted or a new IEP was developed.',
      where: 'Transfer records, prior IEP, and the receiving school IEP.',
      evidence: ['Prior IEP located', 'Comparable services documented', 'Adoption or new IEP documented'],
      source: '34 CFR §300.323(e)–(f)', status: 'Pending Verification', district: '' },
    { id: 'A7', section: 'A', title: 'Amendment documentation', fix: 'now',
      show: { events: ['amendment'] },
      verify: 'The amendment is documented, dated, and the parent (or adult student) received a copy of the revised IEP on request.',
      where: 'Amendment record in the district system.',
      evidence: ['Amendment located', 'Amendment date checked', 'Changed sections identifiable'],
      source: '34 CFR §300.324(a)(4), (a)(6)', status: 'Pending Verification', district: '' },

    // B. Meeting documentation
    { id: 'B1', section: 'B', title: 'Parent meeting notification', fix: 'evidence',
      verify: 'A meeting notice went to the parent (or adult student) and states purpose, time, location, and who will attend.',
      where: 'Notice of meeting in the folder or district system.',
      evidence: ['Meeting notice located', 'Notice and meeting dates checked', 'Parent participation efforts reviewed', 'Required participants verified'],
      source: '34 CFR §300.322(a)–(b)', status: 'Pending Verification', district: '' },
    { id: 'B2', section: 'B', title: 'Meeting notice dates', fix: 'evidence',
      verify: 'The notice was provided early enough to give the parent an opportunity to attend, per the verified district timeline.',
      where: 'Notice date compared with the meeting date.',
      evidence: ['Notice date located', 'Meeting date located', 'Interval checked against the verified timeline'],
      source: '34 CFR §300.322(a)(1); district timeline not yet verified', status: 'Pending Verification', district: '' },
    { id: 'B3', section: 'B', title: 'Required team participation', fix: 'meeting',
      verify: 'Required IEP team roles were present, or an excusal is documented for any absent member.',
      where: 'Participant list on the IEP.',
      evidence: ['Participants listed by role', 'General and special education teachers listed', 'Excusal documented for any absent required member'],
      source: '34 CFR §300.321', status: 'Pending Verification', district: '' },
    { id: 'B4', section: 'B', title: 'Conference notes', fix: 'now',
      verify: 'Conference notes summarize the discussion and decisions made at the meeting.',
      where: 'Conference notes section or attachment.',
      evidence: ['Conference notes located', 'Notes reflect decisions made', 'Notes dated to the meeting'],
      source: 'District practice; not yet verified', status: 'Pending Verification', district: '' },
    { id: 'B5', section: 'B', title: 'Parent participation efforts', fix: 'evidence',
      verify: 'If the parent did not attend, the school documented its attempts to arrange a mutually agreed time and place.',
      where: 'Contact logs and notice attempts.',
      evidence: ['Parent attendance checked', 'Contact attempts documented if parent absent', 'Alternative participation methods offered'],
      source: '34 CFR §300.322(c)–(d)', status: 'Pending Verification', district: '' },
    { id: 'B6', section: 'B', title: 'Prior written notice', fix: 'evidence',
      verify: 'Written notice describes the action proposed or refused, the reasons, and the options considered.',
      where: 'Notice of proposal or refusal.',
      evidence: ['Prior written notice located', 'Action and reasons described', 'Dated appropriately'],
      source: '34 CFR §300.503', status: 'Pending Verification', district: '' },
    { id: 'B7', section: 'B', title: 'Procedural safeguards', fix: 'evidence',
      verify: 'The procedural safeguards notice was provided at least once in the school year and at required events.',
      where: 'Notice record or acknowledgment in the folder or system.',
      evidence: ['Safeguards notice record located', 'Date within the school year checked'],
      source: '34 CFR §300.504', status: 'Pending Verification', district: '' },

    // C. IEP content
    { id: 'C1', section: 'C', title: 'Present levels of academic and functional performance', fix: 'meeting',
      verify: 'Present levels describe current performance and how the disability affects progress in the general curriculum.',
      where: 'Present levels section of the IEP.',
      evidence: ['Academic performance described', 'Functional performance described', 'Impact of disability stated'],
      source: '34 CFR §300.320(a)(1)', status: 'Pending Verification', district: '' },
    { id: 'C2', section: 'C', title: 'Measurable annual goals', fix: 'meeting',
      verify: 'Each annual goal is measurable and connects to a need named in the present levels.',
      where: 'Goals section of the IEP.',
      evidence: ['Goals located', 'Goals are measurable', 'Goals align with identified needs'],
      source: '34 CFR §300.320(a)(2)', status: 'Pending Verification', district: '' },
    { id: 'C3', section: 'C', title: 'Services and supports', critical: true, fix: 'meeting',
      verify: 'Special education, related services, and supports are stated for each identified need.',
      where: 'Services section of the IEP.',
      evidence: ['Services listed', 'Services connect to goals and needs', 'Supports for school personnel stated where applicable'],
      source: '34 CFR §300.320(a)(4)', status: 'Pending Verification', district: '' },
    { id: 'C4', section: 'C', title: 'Frequency and duration', fix: 'meeting',
      verify: 'Each service shows how often and how long it is provided.',
      where: 'Services table of the IEP. Read split table cells carefully.',
      evidence: ['Frequency stated for each service', 'Duration stated for each service'],
      source: '34 CFR §300.320(a)(7)', status: 'Pending Verification', district: '' },
    { id: 'C5', section: 'C', title: 'Service location', fix: 'meeting',
      verify: 'Each service shows where it is provided.',
      where: 'Services table of the IEP.',
      evidence: ['Location stated for each service'],
      source: '34 CFR §300.320(a)(7)', status: 'Pending Verification', district: '' },
    { id: 'C6', section: 'C', title: 'IEP start and end dates', fix: 'system',
      verify: 'Service start and end dates are present and fall within the IEP period.',
      where: 'IEP cover page and services table.',
      evidence: ['Start dates located', 'End dates located', 'Dates fall within the IEP period'],
      source: '34 CFR §300.320(a)(7)', status: 'Pending Verification', district: '' },
    { id: 'C7', section: 'C', title: 'Accommodations', fix: 'meeting',
      verify: 'Classroom accommodations are specific enough for teachers to implement.',
      where: 'Accommodations section of the IEP.',
      evidence: ['Accommodations listed', 'Accommodations are specific and implementable'],
      source: '34 CFR §300.320(a)(4)', status: 'Pending Verification', district: '' },
    { id: 'C8', section: 'C', title: 'Assessment accommodations', fix: 'meeting',
      verify: 'Accommodations for state and district assessments are stated, or none are needed.',
      where: 'Assessment section of the IEP.',
      evidence: ['Assessment participation section located', 'Assessment accommodations stated or none needed'],
      source: '34 CFR §300.320(a)(6)(i)', status: 'Pending Verification', district: '' },
    { id: 'C9', section: 'C', title: 'Placement and least restrictive environment', fix: 'meeting',
      verify: 'The IEP explains the extent, if any, the student will not participate with nondisabled peers.',
      where: 'Placement and LRE section of the IEP.',
      evidence: ['Placement located', 'Explanation of non-participation stated'],
      source: '34 CFR §300.320(a)(5); §§300.114–300.116', status: 'Pending Verification', district: '' },
    { id: 'C10', section: 'C', title: 'ESY consideration and determination', fix: 'system',
      verify: 'The team considered extended school year services and recorded a determination.',
      where: 'ESY section of the IEP. Often locked after submission.',
      evidence: ['ESY section located', 'Determination recorded'],
      source: '34 CFR §300.106', status: 'Pending Verification', district: '' },

    // D. Transition
    { id: 'D1', section: 'D', title: 'Age-appropriate transition assessments', fix: 'meeting',
      show: { minAge: 'transition' },
      verify: 'Transition assessments are named and inform the postsecondary goals.',
      where: 'Transition section of the IEP.',
      evidence: ['Assessments named', 'Assessments are age-appropriate', 'Results inform goals'],
      source: '34 CFR §300.320(b)(1); Florida start age pending verification', status: 'Pending Verification', district: '' },
    { id: 'D2', section: 'D', title: 'Postsecondary goals', fix: 'meeting',
      show: { minAge: 'transition' },
      verify: 'Measurable postsecondary goals address training or education, employment, and independent living where appropriate.',
      where: 'Transition section of the IEP.',
      evidence: ['Education or training goal', 'Employment goal', 'Independent living goal considered'],
      source: '34 CFR §300.320(b)(1)', status: 'Pending Verification', district: '' },
    { id: 'D3', section: 'D', title: 'Transition services', fix: 'meeting',
      show: { minAge: 'transition' },
      verify: 'Transition services help the student reach the postsecondary goals.',
      where: 'Transition services section of the IEP.',
      evidence: ['Transition services listed', 'Services connect to postsecondary goals'],
      source: '34 CFR §300.320(b)(2)', status: 'Pending Verification', district: '' },
    { id: 'D4', section: 'D', title: 'Course of study', fix: 'meeting',
      show: { minAge: 'transition' },
      verify: 'The course of study supports the postsecondary goals and diploma pathway.',
      where: 'Transition section of the IEP.',
      evidence: ['Course of study stated', 'Aligns with goals and diploma pathway'],
      source: '34 CFR §300.320(b)(2); Florida diploma requirements pending verification', status: 'Pending Verification', district: '' },
    { id: 'D5', section: 'D', title: 'Agency participation', fix: 'evidence',
      show: { minAge: 'transition', flag: 'agency' },
      verify: 'An agency likely to provide or pay for transition services was invited, with consent.',
      where: 'Meeting notice and consent for agency invitation.',
      evidence: ['Agency invitation located', 'Consent for invitation located'],
      source: '34 CFR §300.321(b)(3); §300.322(b)(2)', status: 'Pending Verification', district: '' },
    { id: 'D6', section: 'D', title: 'Age-16 requirements', fix: 'meeting',
      show: { minAge: 16 },
      verify: 'Requirements that begin at age 16 are documented, per the verified Florida rule.',
      where: 'Transition section of the IEP.',
      evidence: ['Age-16 items located', 'Checked against the verified Florida rule'],
      source: '34 CFR §300.320(b); Florida-specific items pending verification', status: 'Pending Verification', district: '' },
    { id: 'D7', section: 'D', title: 'Age-17 transfer-of-rights notification', fix: 'meeting',
      show: { minAge: 17 },
      verify: 'At least one year before age 18, the IEP states the student was informed that rights transfer at 18.',
      where: 'Transfer-of-rights statement on the IEP.',
      evidence: ['Statement located', 'Timing checked against the 18th birthday'],
      source: '34 CFR §300.320(c)', status: 'Pending Verification', district: '' },
    { id: 'D8', section: 'D', title: 'Age-18 transfer-of-rights documentation', fix: 'evidence',
      show: { minAge: 18 },
      verify: 'Rights transferred to the student at 18, and notices now go to the student, unless a verified exception applies.',
      where: 'Transfer notice and meeting notices.',
      evidence: ['Transfer notice located', 'Notices addressed to the adult student'],
      source: '34 CFR §300.520; Florida provisions pending verification', status: 'Pending Verification', district: '' },

    // E. Service implementation
    { id: 'E1', section: 'E', title: 'Service delivery logs', fix: 'now',
      verify: 'Logs show services delivered as written in the IEP.',
      where: 'Service logs in the folder or system.',
      evidence: ['Logs located', 'Logs match IEP frequency and duration', 'Missed sessions noted'],
      source: 'IEP implementation, 34 CFR §300.323(c)(2); log format is district practice', status: 'Pending Verification', district: '' },
    { id: 'E2', section: 'E', title: 'Consultation logs', fix: 'now',
      show: { flag: 'consult' },
      verify: 'Consultation logs match the frequency on the IEP and describe the collaboration.',
      where: 'Consultation logs.',
      evidence: ['Logs located', 'Frequency matches the IEP', 'Collaboration content documented'],
      source: 'District practice; not yet verified', status: 'Pending Verification', district: '' },
    { id: 'E3', section: 'E', title: 'Related-service documentation', fix: 'now',
      show: { flag: 'related' },
      verify: 'Related services are documented as delivered.',
      where: 'Related-service provider logs.',
      evidence: ['Provider logs located', 'Delivery matches the IEP'],
      source: '34 CFR §300.34; §300.323(c)(2)', status: 'Pending Verification', district: '' },
    { id: 'E4', section: 'E', title: 'Progress-monitoring evidence', fix: 'now',
      verify: 'Data is collected on each annual goal.',
      where: 'Progress-monitoring data in the folder or system.',
      evidence: ['Goal data located', 'Data covers each goal'],
      source: '34 CFR §300.320(a)(3)(i)', status: 'Pending Verification', district: '' },
    { id: 'E5', section: 'E', title: 'IEP progress reports', fix: 'now',
      verify: 'Progress reports were issued on the schedule stated in the IEP.',
      where: 'Progress reports in the folder or system.',
      evidence: ['Progress reports located', 'Reporting schedule checked'],
      source: '34 CFR §300.320(a)(3)(ii)', status: 'Pending Verification', district: '' },
    { id: 'E6', section: 'E', title: 'Alternate assessment decision', fix: 'meeting',
      show: { flag: 'altAssess' },
      verify: 'The IEP states why the student cannot take the regular assessment and why the alternate assessment fits.',
      where: 'Assessment section of the IEP and supporting documentation.',
      evidence: ['Decision located', 'Reasons stated', 'Supporting documentation located'],
      source: '34 CFR §300.320(a)(6)(ii)', status: 'Pending Verification', district: '' }
  ]
};
